const test = require('ava');
const type = require('.');

test('Base', t => {
    t.is(type(), 'Undefined');
    t.is(type(undefined), 'Undefined');
    t.is(type(null), 'Null');
    t.is(type(''), 'String');
    t.is(type(true), 'Boolean');
    t.is(type(false), 'Boolean');
    t.is(type(0), 'Number');
    t.is(type(-1.5), 'Number');
    t.is(type(NaN), 'Number');
    t.is(type(Infinity), 'Number');
    t.is(type([]), 'Array');
    t.is(type({}), 'Object');
    t.is(type(Object.create(null)), 'Object');
    t.is(type(() => {}), 'Function');
    t.is(type(/^.*$/), 'RegExp');
    t.is(type(new Date()), 'Date');
    t.is(type(new Set()), 'Set');
    t.is(type(new Map()), 'Map');
    t.is(type(new WeakSet()), 'WeakSet');
    t.is(type(new WeakMap()), 'WeakMap');
    t.is(type(Symbol('test')), 'Symbol');
    t.is(type(new Error()), 'Error');
    t.is(type(Math), 'Math');
    t.is(type(JSON), 'JSON');
    t.is(type(new Int8Array()), 'Int8Array');
    t.is(type(new Uint8Array()), 'Uint8Array');
    t.is(type(new Uint8ClampedArray()), 'Uint8ClampedArray');
    t.is(type(new Int16Array()), 'Int16Array');
    t.is(type(new Uint16Array()), 'Uint16Array');
    t.is(type(new Int32Array()), 'Int32Array');
    t.is(type(new Uint32Array()), 'Uint32Array');
    t.is(type(new Float32Array()), 'Float32Array');
    t.is(type(new Float64Array()), 'Float64Array');
    t.is(type(new Promise(() => {})), 'Promise');
});

test('Shortcuts', t => {
    t.true(type.isUndefined());
    t.true(type.isDefined('test'));
    t.true(type.isNull(null));
    t.true(type.isString(''));
    t.true(type.isBoolean(true));
    t.true(type.isNumber(1));
    t.true(type.isArray([]));
    t.true(type.isObject({}));
    t.true(type.isFunction(() => {}));
    t.true(type.isRegExp(/^.*$/));
    t.true(type.isDate(new Date()));
    t.true(type.isSet(new Set()));
    t.true(type.isMap(new Map()));
    t.true(type.isWeakSet(new WeakSet()));
    t.true(type.isWeakMap(new WeakMap()));
    t.true(type.isSymbol(Symbol('test')));
    t.true(type.isError(new Error()));
    t.true(type.isPromise(new Promise(() => {})));

    t.false(type.isUndefined('test'));
    t.false(type.isDefined());
    t.false(type.isNull('null'));
    t.false(type.isString(true));
    t.false(type.isBoolean('true'));
    t.false(type.isNumber('1'));
    t.false(type.isArray({length: 1}));
    t.false(type.isObject(null));
    t.false(type.isFunction(global));
    t.false(type.isRegExp('/^.*$/'));
    t.false(type.isDate('Sat Dec 23 2017 18:44:45 GMT+0300 (MSK)'));
    t.false(type.isSet(new WeakSet()));
    t.false(type.isMap(new WeakMap()));
    t.false(type.isWeakSet(new Set()));
    t.false(type.isWeakMap(new Map()));
    t.false(type.isSymbol([Symbol('test')]));
    t.false(type.isError(Error));
    t.false(type.isPromise(Promise.all));
});
